import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { Store } from '@ngrx/store';
import { MatSnackBar } from '@angular/material/snack-bar'; // Import MatSnackBar
import { addOrder } from '../store/Order/order.actions';
import { ProductService } from '../product-service.service';
import { Order, OrderItem } from '../models/order.model';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-place-order',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './place-order.component.html',
  styleUrls: ['./place-order.component.scss'],
})
export class PlaceOrderComponent {
  products$ = this.productService.getProducts();
  selectedProducts: OrderItem[] = [];
  quantity: number = 1; // Add quantity property

  constructor(
    private store: Store,
    private productService: ProductService,
    private router: Router,
    private snackBar: MatSnackBar // Inject MatSnackBar
  ) {}

  addProduct(productId: number, quantity: number) {
    this.selectedProducts.push({ 
      id: 0, // Will be generated by the backend
      productId, 
      quantity, 
      orderId: 0 // Will be set when the order is created
    });
    this.snackBar.open('Product added successfully!', 'Close', {
      duration: 3000, // Show for 3 seconds
    });
  }

  placeOrder() {
    const order: Order = {
      id: 0, // Will be generated by the backend
      orderItems: this.selectedProducts,
    };
    console.log('Placing order:', order); // Debugging
    this.store.dispatch(addOrder({ order })); // Dispatch the addOrder action
    this.router.navigate(['/orders']);
  }
}