// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductMicroservice.Data;

#nullable disable

namespace product.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250315034343_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ProductMicroservice.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "High-performance laptop",
                            Name = "Laptop",
                            Price = 1200.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Description = "Latest smartphone model",
                            Name = "Smartphone",
                            Price = 800.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            Description = "Portable tablet device",
                            Name = "Tablet",
                            Price = 500.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            Description = "Noise-cancelling headphones",
                            Name = "Headphones",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Electronics",
                            Description = "Fitness tracking smartwatch",
                            Name = "Smartwatch",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            Description = "27-inch 4K monitor",
                            Name = "Monitor",
                            Price = 400.00m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Electronics",
                            Description = "Mechanical gaming keyboard",
                            Name = "Keyboard",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Electronics",
                            Description = "Wireless ergonomic mouse",
                            Name = "Mouse",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Electronics",
                            Description = "All-in-one laser printer",
                            Name = "Printer",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Electronics",
                            Description = "DSLR camera with 24MP",
                            Name = "Camera",
                            Price = 700.00m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Electronics",
                            Description = "Bluetooth portable speaker",
                            Name = "Speaker",
                            Price = 100.00m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Electronics",
                            Description = "4K HD drone with camera",
                            Name = "Drone",
                            Price = 600.00m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Electronics",
                            Description = "Wi-Fi 6 router",
                            Name = "Router",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Electronics",
                            Description = "1TB portable SSD",
                            Name = "External SSD",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Electronics",
                            Description = "Next-gen gaming console",
                            Name = "Gaming Console",
                            Price = 500.00m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Home Appliances",
                            Description = "Automatic drip coffee maker",
                            Name = "Coffee Maker",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Home Appliances",
                            Description = "High-speed blender",
                            Name = "Blender",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Home Appliances",
                            Description = "Compact microwave oven",
                            Name = "Microwave",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Home Appliances",
                            Description = "4-slice toaster",
                            Name = "Toaster",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Home Appliances",
                            Description = "Bagless vacuum cleaner",
                            Name = "Vacuum Cleaner",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Home Appliances",
                            Description = "HEPA air purifier",
                            Name = "Air Purifier",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Home Appliances",
                            Description = "Stainless steel electric kettle",
                            Name = "Electric Kettle",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Home Appliances",
                            Description = "Automatic rice cooker",
                            Name = "Rice Cooker",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Home & Office",
                            Description = "LED desk lamp",
                            Name = "Desk Lamp",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 25,
                            Category = "Home & Office",
                            Description = "Ergonomic office chair",
                            Name = "Office Chair",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 26,
                            Category = "Home & Office",
                            Description = "Adjustable standing desk",
                            Name = "Desk",
                            Price = 300.00m
                        },
                        new
                        {
                            Id = 27,
                            Category = "Stationery",
                            Description = "Spiral-bound notebook",
                            Name = "Notebook",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 28,
                            Category = "Stationery",
                            Description = "Ballpoint pen (pack of 10)",
                            Name = "Pen",
                            Price = 10.00m
                        },
                        new
                        {
                            Id = 29,
                            Category = "Stationery",
                            Description = "Heavy-duty stapler",
                            Name = "Stapler",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 30,
                            Category = "Home & Office",
                            Description = "Cross-cut paper shredder",
                            Name = "Paper Shredder",
                            Price = 100.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
